import { jsPDF } from "jspdf";

/**
 * Generate a filled PDF from parsed form data
 * Matches Python backend's generate_filled_pdf function
 */
export function generateFilledPDF(
  parsed: Record<string, any>,
  rawImageBytes?: Buffer
): Buffer {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "letter",
  });

  const width = doc.internal.pageSize.getWidth();
  const height = doc.internal.pageSize.getHeight();
  const xLeft = 50;
  const xRight = width - 50;
  let y = 50;
  const lineHeight = 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Inkference AI - Extracted Form Data", xLeft, y);
  y += 30;

  if (parsed.formType) {
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 200);
    doc.text(`Form Type: ${parsed.formType}`, xLeft, y);
    doc.setTextColor(0, 0, 0);
    y += 25;
  }

  doc.setDrawColor(200, 200, 200);
  doc.line(xLeft, y, xRight, y);
  y += 20;

  // Body content
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const writePair = (k: string, v: any) => {
    // Skip internal fields
    if (k === "confidenceHints" || k === "formType") return;

    if (y > height - 60) {
      doc.addPage();
      y = 50;
    }

    doc.setFont("helvetica", "bold");
    doc.text(`${formatFieldName(k)}:`, xLeft, y);
    
    doc.setFont("helvetica", "normal");
    const valueStr = formatValue(v);
    
    const maxWidth = xRight - xLeft - 150;
    const lines = doc.splitTextToSize(valueStr, maxWidth);
    doc.text(lines, xLeft + 150, y);
    
    y += lineHeight * lines.length;

    if (parsed.confidenceHints && parsed.confidenceHints[k]) {
      const confidence = parsed.confidenceHints[k];
      const confidencePercent = Math.round(confidence * 100);
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(`(${confidencePercent}% confidence)`, xLeft + 150, y);
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      y += 5;
    }

    y += 5; // spacing between fields
  };

  const sortedKeys = Object.keys(parsed).sort((a, b) => {
    // Form type first, then alphabetical
    if (a === 'formType') return -1;
    if (b === 'formType') return 1;
    return a.localeCompare(b);
  });

  for (const key of sortedKeys) {
    writePair(key, parsed[key]);
  }

  y = height - 30;
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by Inkference AI • ${new Date().toLocaleString()}`, xLeft, y);

  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
  return pdfBuffer;
}

function formatFieldName(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, str => str.toUpperCase())
    .trim();
}

function formatValue(v: any): string {
  if (v === null || v === undefined) return "N/A";
  if (typeof v === "object") return JSON.stringify(v, null, 2);
  return String(v);
}
